# Generated by Django 5.0 on 2025-09-17 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerFeedback",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Customer name (optional)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        help_text="Customer's thoughts on the checkout process"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        help_text="Associated order",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Feedback",
                "verbose_name_plural": "Customer Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
