# Generated by Django 5.1.3 on 2025-09-20 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_petition_petitionupvote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="petition",
            options={"ordering": ["-upvotes", "-created_at"]},
        ),
    ]
